spring.application.name=skyface
spring.profiles.active=dev

joinfaces.primefaces.theme=saga
joinfaces.jsf.facelets-refresh-period=1
server.servlet.context-parameters.javax.faces.DEFAULT_SUFFIX=.xhtml
